### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by hoangelos** [Agilicus/kustomize-sops#3]
I am kinda stuck with this one and can't figure it out.

`2usmhalliday2:kustomize-sops halliday$ go build -buildmode plugin -o $OUTDIR/kustomize-sops.so kustomize-sops.go
2usmhalliday2:kustomize-sops halliday$ kustomize build --enable_alpha_goplugins_accept_panic_risk
Error: generating legacy configMaps and secrets: secretgenerator: [{{ mysecrets  {[] [] } [{go kustomize-sops [CAT DOG]}]} }]: NewResMapFromSecretArgs: plugins: : plugin.Open("/Users/halliday/.config/kustomize/plugin/kvSources/kustomize-sops"): plugin was built with a different version of package gopkg.in/yaml.v2`

**Comment by donbowman** [comment]
i have to do a bit of work, the upstream has changed. Let me make a change to it compiles again.
To workaround, you can checkout kustomize 2.0.1 and then build.

That is the challenge these `goplugins` create, they area highly brittle.

**Comment by donbowman** [comment]
resolved w/ 18a373d65d51d59497d465c9c4faffc1bee7343a.
updated instructed, added go.mod
