### ISSUE TITLE
protobuff dependency

### ISSUE THREAD

**Issue by rosscdh** [Agilicus/kustomize-sops#6]
Hey there, firstly awesome plugin thank you for your efforts.

As you noted about brittle dependencies in go am currently investigating a 

```
Error: loading generator plugins: plugin /root/.config/kustomize/plugin/kustomize-sops/v1/sopssecret/SopsSecret fails to load: plugin.Open("/root/.config/kustomize/plugin/kustomize-sops/v1/sopssecret/SopsSecret"): plugin was built with a different version of package github.com/golang/protobuf/proto
make: *** [generate] Error 1
```

error in the latest version of kustomize i suspect, but may affect this implementation

**Comment by donbowman** [comment]
You can pin it in the makefile by sha as a workaround.

You can also consider using https://github.com/Agilicus/kustomize-plugins/tree/master/agilicus/v1 which achieve the same and more goals, without the brittle use of go.

**Comment by rosscdh** [comment]
both are great tips.. ill go with your recommended way :) thanks

**Comment by rosscdh** [comment]
i think the issue is being caused by sops protobuff btw..

kustomize uses golang/protobuf 1.3.1 but sops 1.3.2

**Comment by rosscdh** [comment]
sorry 1 last thing.. 

https://github.com/Agilicus/kustomize-plugins/tree/master/agilicus/v1/secrettransformer is what you meant?

**Comment by donbowman** [comment]
try 
https://github.com/Agilicus/kustomize-plugins/tree/master/agilicus/v1/secretstringdatatransformer
or
https://github.com/Agilicus/kustomize-plugins/tree/master/agilicus/v1/secretgenerator

**Comment by rosscdh** [comment]
yep just noticing hte docs are a little thin in areas will be happy to create a PR with updates just have to understand how to use the aspects

**Comment by rosscdh** [comment]
specifically https://github.com/Agilicus/kustomize-plugins/tree/master/agilicus/v1/secretgenerator seems the closest but am i reading this right.. its just a python file iinteresting this opens possiblities..

**Comment by rosscdh** [comment]
ah ok reading code all good just the docs are thin.. ill update docs

**Comment by rosscdh** [comment]
So, just an update for you and a question

1. what will the status of this project be now that sops has been removed from kustomize?
2. I've forked and fixed the references and will have to maintain for the moment. Tho do you have an idea of what the future holds? I imagine "plugins" as per that which you recommended? in which case ill get some time scheduled to contribute?

**Comment by donbowman** [comment]
sops was never in kustomize.
early on in kustomize it added `exec plugins`. Then all of a sudden they removed them, and added `go plugins`. So i moved my exect plugin over to go. But it was very very brittle, i'm not sure how anyone can use go plugins with any code.
then kustomize re-added exec plugins.
All our current dev is on the exec plugins. I still use the kustomize-sops (as as go plugin) in a few spots, but might eventually drop it.

**Comment by rosscdh** [comment]
Ok this is fantastic news (as you have, I too have a growing irritation
with a number of aspects of go-lang for all its good).

Would you mind if I synced the secretsGenerator so that its a little more
like the the sops-plugin? maybe as a v2? (subjectively it feels cleaner?)

Ill try get some time scheduled in the next sprint for it.
